name: Build JoseloFarias APK (Release)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: keystore/key.jks
          encodedString: ${{ secrets.SIGN_KEY }}
      - name: Build JoseloFarias release APK
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleJoselofariasRelease --no-build-cache --rerun-tasks
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Inure-JoseloFarias
          path: app/build/outputs/apk/joselofarias/release/app-joselofarias-release.apk
